
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: 'TRACE '
spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: Byrong11
    url: jdbc:sqlserver://localhost:1433;databaseName=GPH;encrypt=true;trustServerCertificate=true;
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        formatsql: true
    show-sql: true
    
server: 
  port: ${PORT:0}
# Config de el servidor  

eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  
  instance:
    instance-id: ${spring.application.name}:${random.value}  
